### ISSUE TITLE
Error en link sección "Un recorrido por swift"

### ISSUE THREAD

**Issue by KrlitosForever** [trsplms/swift-book-es#24]
Hola estaba leyendo la documentación en la sección
**Un recorrido por swift**
![image](https://user-images.githubusercontent.com/7423579/234377216-8c0e6460-bad8-4aa1-aa9a-9c8703ade60e.png)

al darle clic genera lo siguiente:
![image](https://user-images.githubusercontent.com/7423579/234377638-b4d8c246-951f-4966-a8b1-7350c0fd1418.png)

Saludos desde Chile.

**Comment by trsplms** [comment]
Hola, Carlos. Sí, ya lo había notado. Apple hizo algunos cambios al contenido del libro con la nueva versión de Swift. Estoy trabajando en agregar los cambios y actualizar todo. Para esta semana deberían verse reflejado los cambios en producción.
